import type React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  page: {
    minHeight: '100vh',
    backgroundColor: '#0f172a',
    color: '#e2e8f0',
    padding: '24px',
  },
  container: {
    maxWidth: '760px',
    margin: '0 auto',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  title: {
    fontSize: '24px',
    fontWeight: 700,
    marginBottom: 4,
  },
  subtitle: {
    fontSize: '15px',
    color: '#cbd5e1',
    marginBottom: 8,
  },
  inputGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  label: {
    color: '#cbd5e1',
    fontSize: '14px',
  },
  labelRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    flexWrap: 'wrap',
  },
  hintWrapper: {
    position: 'relative',
    display: 'inline-flex',
    alignItems: 'center',
  },
  hintIcon: {
    width: 18,
    height: 18,
    borderRadius: 999,
    border: '1px solid #38bdf8',
    backgroundColor: 'transparent',
    color: '#38bdf8',
    fontSize: '12px',
    fontWeight: 700,
    lineHeight: '16px',
    cursor: 'pointer',
    padding: 0,
  },
  hintBubble: {
    position: 'absolute',
    top: 'calc(100% + 6px)',
    left: '50%',
    transform: 'translateX(-50%)',
    minWidth: '220px',
    maxWidth: '260px',
    backgroundColor: '#0b1220',
    color: '#e2e8f0',
    border: '1px solid #1e293b',
    borderRadius: 10,
    padding: '8px 10px',
    fontSize: '12px',
    lineHeight: 1.35,
    boxShadow: '0 8px 16px rgba(0, 0, 0, 0.25)',
    zIndex: 10,
  },
  input: {
    backgroundColor: '#1e293b',
    color: '#e2e8f0',
    borderRadius: 10,
    padding: '12px',
    border: '1px solid #334155',
    fontSize: '15px',
    outline: 'none',
  },
  button: {
    backgroundColor: '#38bdf8',
    color: '#0b172a',
    fontWeight: 700,
    fontSize: '16px',
    padding: '14px',
    border: 'none',
    borderRadius: 10,
    cursor: 'pointer',
    marginTop: '12px',
  },
  secondaryButton: {
    backgroundColor: 'transparent',
    color: '#38bdf8',
    fontWeight: 700,
    fontSize: '16px',
    padding: '14px',
    border: '1px solid #38bdf8',
    borderRadius: 10,
    cursor: 'pointer',
    marginTop: '12px',
  },
  actionButton: {
    flex: 1,
    minWidth: '200px',
    textAlign: 'center',
  },
  searchRow: {
    display: 'flex',
    gap: '8px',
    flexWrap: 'wrap',
    alignItems: 'center',
  },
  error: {
    color: '#f87171',
    fontWeight: 600,
    margin: 0,
  },
  row: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#1e293b',
    padding: '12px',
    borderRadius: 10,
  },
  rowLabel: {
    color: '#cbd5e1',
    fontSize: '14px',
  },
  rowValue: {
    color: '#e2e8f0',
    fontSize: '16px',
    fontWeight: 700,
  },
  section: {
    backgroundColor: '#0b1220',
    borderRadius: 10,
    padding: '12px',
    border: '1px solid #1e293b',
    marginTop: '8px',
  },
  sectionTitle: {
    color: '#e2e8f0',
    fontWeight: 700,
    marginBottom: 6,
    fontSize: '14px',
  },
  sectionText: {
    color: '#cbd5e1',
    fontSize: '13px',
    marginBottom: 2,
  },
  searchInput: {
    minWidth: '240px',
  },
  searchList: {
    listStyle: 'none',
    padding: 0,
    margin: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  searchItem: {
    backgroundColor: '#1e293b',
    border: '1px solid #334155',
    borderRadius: 10,
    padding: '10px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '12px',
  },
  searchMeta: {
    color: '#cbd5e1',
    fontSize: '13px',
  },
};
